<a href="https://colab.research.google.com/github/gfeyzakorkmaz/gfeyzakorkmaz/blob/main/pythonday41.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [2]:
path = '/content/drive/MyDrive/Dataset/complex_marketing_data_enriched.xlsx'

In [3]:
df = pd.read_excel(path)

In [5]:
import numpy as np

spend = np.random.uniform(0, 100, size=1000)

purchase_prob = 1 / (1 + np.exp(-0.1 * (spend - 50)))

purchases = np.random.binomial(1, purchase_prob)

total_purchases = np.sum(purchases)
avg_purchase_prob = np.mean(purchase_prob)
print(f"Total Purchases: {total_purchases}, Avg Purchase Probability: {avg_purchase_prob:.2f}")

Total Purchases: 494, Avg Purchase Probability: 0.51


In [7]:
sales = np.random.normal(500, 50, size=52)

weights = np.linspace(1, 0, 10)
weights /= weights.sum()

trend = np.convolve(sales, weights, mode='valid')

print(f"Last 5 Weeks of Trend: {trend[-5:]}")

Last 5 Weeks of Trend: [521.22947511 512.97902842 515.07580479 523.1982221  515.92273408]


In [8]:
revenues = np.random.pareto(2, size=1000) * 1000

revenues_sorted = np.sort(revenues)
cumulative_revenue = np.cumsum(revenues_sorted) / np.sum(revenues_sorted)
cumulative_customers = np.linspace(0, 1, len(revenues))

print(f"Cumulative Revenue (First 10): {cumulative_revenue[:10]}")
print(f"Cumulative Customers (First 10): {cumulative_customers[:10]}")

Cumulative Revenue (First 10): [5.84490778e-07 1.25118606e-06 2.67886089e-06 4.68009407e-06
 6.83580582e-06 9.21508693e-06 1.17143182e-05 1.51425043e-05
 1.88716054e-05 2.26586214e-05]
Cumulative Customers (First 10): [0.         0.001001   0.002002   0.003003   0.004004   0.00500501
 0.00600601 0.00700701 0.00800801 0.00900901]


In [9]:
X = np.random.rand(100, 2) * 100
y = 5 * X[:, 0] + 2 * X[:, 1] + np.random.normal(0, 5, 100)

ridge_lambda = 1
XTX = np.dot(X.T, X) + ridge_lambda * np.eye(X.shape[1])
XTy = np.dot(X.T, y)
coefficients = np.linalg.solve(XTX, XTy)

print(f"Ridge Regression Coefficients: {coefficients}")

Ridge Regression Coefficients: [5.01348594 1.99679234]


In [10]:
import numpy as np

transition_matrix = np.array([[0.8, 0.2],
                              [0.0, 1.0]])

state = np.array([1, 0])

for i in range(10):
    state = np.dot(state, transition_matrix)
    print(f"Period {i+1}: Active={state[0]:.2f}, Churned={state[1]:.2f}")

Period 1: Active=0.80, Churned=0.20
Period 2: Active=0.64, Churned=0.36
Period 3: Active=0.51, Churned=0.49
Period 4: Active=0.41, Churned=0.59
Period 5: Active=0.33, Churned=0.67
Period 6: Active=0.26, Churned=0.74
Period 7: Active=0.21, Churned=0.79
Period 8: Active=0.17, Churned=0.83
Period 9: Active=0.13, Churned=0.87
Period 10: Active=0.11, Churned=0.89


In [11]:
spend = np.linspace(1, 100, 100)
sales = 50 * np.log(spend) + np.random.normal(0, 5, 100)

log_spend = np.log(spend)
log_sales = np.log(sales)
elasticity = np.polyfit(log_spend, log_sales, 1)[0]

print(f"Elasticity of Marketing Spend: {elasticity:.2f}")

Elasticity of Marketing Spend: 0.44


In [12]:
cohorts = np.random.uniform(0.6, 1.0, size=(5, 10))
retention_rates = np.cumprod(cohorts, axis=1)

print("Retention Rates by Cohort:")
print(retention_rates)

Retention Rates by Cohort:
[[0.81994839 0.66350323 0.43678881 0.34690896 0.21745401 0.16261529
  0.1500324  0.11527392 0.08305893 0.05334198]
 [0.91768967 0.81065236 0.61011823 0.58224754 0.52928464 0.32706597
  0.27428583 0.21223985 0.16299336 0.14457864]
 [0.76129475 0.73296455 0.46735532 0.35670423 0.27013083 0.19117105
  0.12241748 0.10299466 0.09863046 0.06994124]
 [0.60025566 0.45842332 0.41689219 0.28712647 0.26966867 0.16702911
  0.15472872 0.13033036 0.0961668  0.0771292 ]
 [0.84909878 0.69335267 0.62406188 0.61442263 0.44851332 0.31166442
  0.21439576 0.13547815 0.1300087  0.09056424]]


In [14]:
import numpy as np
from scipy.optimize import minimize

def revenue(spend):
    return -(100 * np.sqrt(spend) - 0.05 * spend**2)


result = minimize(revenue, x0=50, bounds=[(0, 100)])
optimal_spend = result.x[0]

print(f"Optimal Ad Spend: {optimal_spend:.2f}")

Optimal Ad Spend: 63.00


In [16]:
clicks_a = np.random.binomial(100, 0.05, size=1000)
clicks_b = np.random.binomial(100, 0.06, size=1000)

posterior_a = np.mean(clicks_a) / 100
posterior_b = np.mean(clicks_b) / 100


print(f"Posterior Probabilities (A, B): {posterior_a:.2f}, {posterior_b:.2f}")

Posterior Probabilities (A, B): 0.05, 0.06


In [17]:
channels = np.random.rand(10, 100)

correlation_matrix = np.corrcoef(channels)

print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[ 1.         -0.13608241  0.03276369 -0.02425839  0.01867533 -0.02351792
  -0.0405828  -0.05965069  0.07387605  0.04575443]
 [-0.13608241  1.         -0.11540008 -0.01156253 -0.02038903 -0.05509019
  -0.1608362  -0.14560033 -0.04352254  0.17461721]
 [ 0.03276369 -0.11540008  1.          0.03852445  0.19765206 -0.09533818
  -0.03513582 -0.08488548 -0.15478445  0.19139733]
 [-0.02425839 -0.01156253  0.03852445  1.         -0.01634433  0.09125383
  -0.09629975  0.17822706  0.05033987 -0.00402015]
 [ 0.01867533 -0.02038903  0.19765206 -0.01634433  1.          0.08417017
  -0.19804004 -0.07207183 -0.00504743  0.01635713]
 [-0.02351792 -0.05509019 -0.09533818  0.09125383  0.08417017  1.
   0.08176053 -0.00226066  0.09534988  0.09050106]
 [-0.0405828  -0.1608362  -0.03513582 -0.09629975 -0.19804004  0.08176053
   1.         -0.06398333  0.02047059  0.03737654]
 [-0.05965069 -0.14560033 -0.08488548  0.17822706 -0.07207183 -0.00226066
  -0.06398333  1.          0.05904248 -

In [19]:
predicted = np.random.rand(1000)
actual = np.random.binomial(1, predicted)

sorted_indices = np.argsort(-predicted)
sorted_actual = actual[sorted_indices]
cumulative_responses = np.cumsum(sorted_actual)

lift = cumulative_responses / np.arange(1, len(actual) + 1)

print(f"lift (Top 10%): {lift[int(0.1 * len(lift))]:.2f}")

lift (Top 10%): 0.96


In [20]:
conversion_rates = np.random.beta(10, 90, size=10000)
mean_conversion = np.mean(conversion_rates)
confidence_interval = np.percentile(conversion_rates, [2.5, 97.5])

print(f"Mean Conversion Rate: {mean_conversion:.2f}")
print(f"95% Confidence Interval: {confidence_interval}")

Mean Conversion Rate: 0.10
95% Confidence Interval: [0.04977899 0.1652764 ]


In [21]:
spend = np.random.normal(5000, 1000, 100)
customers = np.random.poisson(10, 100)
cac = spend / customers

print(f"Mean CAC: {np.mean(cac):.2f}, Std Dev: {np.std(cac):.2f}")

Mean CAC: 525.02, Std Dev: 196.45


In [23]:
metrics = np.random.normal(100, 20, 50)

z_scores = (metrics - np.mean(metrics)) / np.std(metrics)
anomalies = np.where(np.abs(z_scores) > 2)[0]

print(f"Anomalies Metric Indices: {anomalies}")

Anomalies Metric Indices: [ 9 34]


In [24]:
recency = np.random.exponential(scale=30, size=1000)
frequency = np.random.poisson(10, size=1000)
monetary = np.random.gamma(2, scale=500, size=1000)

rfm_scores = np.vstack([
    (recency - np.min(recency)) / (np.max(recency) - np.min(recency)),
    (frequency - np.min(frequency)) / (np.max(frequency) - np.min(frequency)),
    (monetary - np.min(monetary)) / (np.max(monetary) - np.min(monetary))
]).T

print(f"Sample RFM Scores (First 5):\n{rfm_scores[:5]}")

Sample RFM Scores (First 5):
[[0.02242828 0.6        0.30315255]
 [0.46205702 0.6        0.56475753]
 [0.01399289 0.55       0.341625  ]
 [0.03964969 0.7        0.11066675]
 [0.04512505 0.6        0.04045033]]
